
import { Nunito } from 'next/font/google'
import '../public/template/css/styles.css'
import '../public/template/css/fontawesome-free/css/all.min.css'
import '../public/template/css/styles.css'
import '../public/template/css/sb-admin-2.min.css'
import { UserProvider } from './context/userContext'
const nunito = Nunito({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <UserProvider>
      <html lang="en">
        <body className={nunito.className}>
            {children}
            <script src="/template/js/jquery.min.js"></script>
            <script src="/template/js/bootstrap.bundle.min.js"></script>
            <script src="/template/js/sb-admin-2.min.js"></script>
            <script src='/template/js/scripts.js'></script>
            <script src='/template/js/tehem-map.js'></script>
    
        
        </body>
    
      </html>
      </UserProvider>
  )
}
